[package]
name = "corrosion"
version = "0.1.0"
edition = "2021"

[features]
"debug-full" = []
"test-suite" = []

[profile.dev]
opt-level = 0
lto = false
panic = "abort"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[dependencies]
